DROP TABLE IF EXISTS ITEMS CASCADE;
CREATE TABLE ITEMS (
                       ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       ITEMNAME VARCHAR(100),
                       PRICE NUMBER(10),
                       QUANTITY NUMBER(10),
                       OPEN VARCHAR(3),
                       REGIONS VARCHAR(255),
                       ITEMTYPE VARCHAR(10),
                       DELIVERYCODE VARCHAR(10),
                       PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS MEMBERS CASCADE;
CREATE TABLE MEMBERS (
                         ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         LOGINID VARCHAR(100),
                         NAME VARCHAR(100),
                         PASSWORD VARCHAR(100),
                         PRIMARY KEY(ID)
);